### ISSUE TITLE
Upgrade to Symfony 6.4 (or maybe 7.0)

### ISSUE THREAD

**Issue by garak** [PUGX/badge-poser#1139]
Symfony [6.4](https://symfony.com/blog/symfony-6-4-0-released) and [7.0](https://symfony.com/blog/symfony-7-0-0-released) were released today! 🎉

We could for sure upgrade to Symfony 6.4 and, if we don't have deprecations, maybe we could also upgrade to 7.0

**Comment by JellyBellyDev** [comment]
done in https://github.com/PUGX/badge-poser/pull/1150
