### ISSUE TITLE
[RedisReader]using mget instead of lot of gets

### ISSUE THREAD

**Issue by liuggio** [PUGX/badge-poser#117]
inside  `totalDataOfAccessesByInterval`
there are a lot of `$value = $this->redis->get($this->getKeyString($interval, $dimension));`
maybe a better implementation could use using `mget`

**Comment by cirpo** [comment]
can't find any references about `totalDataOfAccessesByInterval` in the current master. Is this already solved?

**Comment by liuggio** [comment]
yes it is :*
