### ISSUE TITLE
Flat icons support

### ISSUE THREAD

**Issue by dimsav** [PUGX/badge-poser#143]
I don't see anywhere the support for flat icons. Is this feature already implemented or coming anytime soon?

Thanks!

**Comment by liuggio** [comment]
This is a good idea

**Comment by Fefas** [comment]
+1

**Comment by ramsey** [comment]
+1

**Comment by liuggio** [comment]
anyone want to do this?

**Comment by ramsey** [comment]
I thought about taking a look myself to implement, but I'm not sure how to get badge-poser running locally to implement and test.

I notice that Shields has the ability to add `?style=flat` to the end of the URL to generate flat vs. "plastic" style of badge. I'm not familiar with Buckler (which is what it appears you're using here), but if it follows the Shields standard, then perhaps it's a simple addition to allow users to append `?style=flat` and then pass that through to Buckler?

![Flat badge](https://img.shields.io/badge/style-flat-green.svg?style=flat)
![Plastic badge](https://img.shields.io/badge/style-flat-green.svg?style=plastic)

    ![Flat badge](https://img.shields.io/badge/style-flat-green.svg?style=flat)
    ![Plastic badge](https://img.shields.io/badge/style-flat-green.svg?style=plastic)

**Comment by liuggio** [comment]
Hi this is a symfony2 project and doesn't use buckler 
if you want to run this project the readme https://github.com/PUGX/badge-poser#contribution could help you,

BUT

I think the first step is working at this library 
It uses a library at https://github.com/badges/poser  
and maybe there's to add a new SvgRender called FlatSvgRender or something like that: https://github.com/badges/poser/blob/master/src/Render/SvgRender.php#L29
you should also add some test, when this is fixed the symfony project is the next step.

**Comment by ramsey** [comment]
I'm not sure what the difference is in the projects.

I saw here (#106) that it appears you're using Buckler, which is why I thought you were using Buckler. Sorry for the misunderstanding.

**Comment by liuggio** [comment]
No problem we have decoupled a library from the website 
the library is here https://github.com/badges/poser
We have used bucker but we decided to put it off...

**Comment by liuggio** [comment]
tadaaaaaa https://github.com/badges/poser/pull/3/files 
first step is done
