### ISSUE TITLE
Badges are not served anymore

### ISSUE THREAD

**Issue by mikehaertl** [PUGX/badge-poser#146]
I'm not sure where to report this, so I'll try here. Currently no badges are served anymore. Even the badges on your own github repo are affected:

![pugx badge poser](https://cloud.githubusercontent.com/assets/675062/7681372/1251d8e2-fd70-11e4-9bdc-647f727cb1aa.png)

**Comment by liuggio** [comment]
OMG I've missed the alert email thanks.

**Comment by liuggio** [comment]
thanks  @mikehaertl  for reporting  :+1:

**Comment by mikehaertl** [comment]
Thanks for the quick fix.
