### ISSUE TITLE
Composer Packages that don't exist get a stacktrace displayed in image

### ISSUE THREAD

**Issue by giggsey** [PUGX/badge-poser#147]
Example: https://poser.pugx.org/giggsey/libphonenumber-geocoder/v/stable ![Img](https://poser.pugx.org/giggsey/libphonenumber-geocoder/v/stable)

**Comment by liuggio** [comment]
The packagist API are down and that packages isn't in cache...
Thanks for reporting it should show an invalid badges...

**Comment by giggsey** [comment]
Ahh, I didn't even realise Packagist was down.

**Comment by liuggio** [comment]
btw this is fixed and deployed 
https://github.com/PUGX/badge-poser/commit/e4ae7be993c84d557057bb352016af3a6e65774d 

cc/ @seldaek
