### ISSUE TITLE
Show No release label ?

### ISSUE THREAD

**Issue by euclid1990** [PUGX/badge-poser#150]
My package: https://github.com/euclid1990/php-google-suggest
On Pacakgist: https://packagist.org/packages/euclid1990/php-google-suggest
Current version: 1.0.0
![selection_069](https://cloud.githubusercontent.com/assets/5584709/13765859/c3d67430-ea8f-11e5-97f1-54850f8b5a35.png)

When I insert following markdown:
```
[![Latest Stable Version](https://poser.pugx.org/euclid1990/php-google-suggest/version)](https://packagist.org/packages/euclid1990/php-google-suggest)
```
Its show 
![selection_068](https://cloud.githubusercontent.com/assets/5584709/13765824/6b1c46b2-ea8f-11e5-8e75-902d8464b152.png)

Is it Bug ?

**Comment by giorrrgio** [comment]
Seems okay now, it was probably related to an old image still cached
