### ISSUE TITLE
Trust failed

### ISSUE THREAD

**Issue by rquadling** [PUGX/badge-poser#152]
Not sure how or who can deal with this ...

Using PHPStorm. Reading a README.md with poser badges. Getting ...

![image](https://cloud.githubusercontent.com/assets/12801/14379878/69b4ce8c-fd74-11e5-989d-d32cfcbbdbd7.png)

I don't know if this is a PHPStorm issue or Windows 10.  Or a cert chain issue.

**Comment by rquadling** [comment]
And 10s later I find the issue...

https://community.letsencrypt.org/t/report-issues-when-certificate-is-not-trusted/4743

and a possible fix (PLEASE BE SURE YOU KNOW WHAT YOU ARE DOING AND DO IT ONLY IF YOU ARE SURE IT IS THE RIGHT THING TO DO) : https://community.letsencrypt.org/t/will-the-cross-root-cover-trust-by-the-default-list-in-the-jdk-jre/134/13

**Comment by liuggio** [comment]
@rquadling woow thanks a lot! 
We used godaddy for a while for their support for opensource projects, but I found this project lets'encrypt interesting...
As far as I understand the solution is only for the client side, and is not a solution for everybody.

But thanks I think we should think about it...

**Comment by rquadling** [comment]
I think the solution that is perfectly reasonable with the following caveats.

1. You trust Let's Encrypt and the certificates that they sign.
2. You use Java and want to Java to trust Let's Encrpyt and the certificates that they sign.

I think the danger is that, as a normal user, I'm in position to evaluate that trust. We rely on the trust built by those that know more than we do.

I've got nothing else to say on this, so close this issue if you feel it is completed.

**Comment by liuggio** [comment]
@rquadling thanks alot, I prefer to not close it now...
