### ISSUE TITLE
LetsEncrypt SSL certificate expiration

### ISSUE THREAD

**Issue by dm** [PUGX/badge-poser#157]
Hi all,

Heads up that https://poser.pugx.org LetsEncrypt certificate is about to expire on June 30th.

Received the SSL warning in PHPStorm, so I presume it's validating and warning close to certificate expiration.

**Comment by cirpo** [comment]
Thanks Daniel,

We will look into it.

Cirpo

On Saturday, 25 June 2016, Daniel Macedo <notifications@github.com> wrote:

> Hi all,
>
> Heads up that https://poser.pugx.org LetsEncrypt certificate is about to
> expire on June 30th.
>
> Received the SSL warning in PHPStorm, so I presume it's validating and
> warning close to certificate expiration.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/PUGX/badge-poser/issues/157>, or mute the thread
> <https://github.com/notifications/unsubscribe/AADINKY9RnhaKmzHsndb8e9KXWDlpp50ks5qPUt4gaJpZM4I-XpK>
> .
>


-- 
@cirpo

mobile:  +44 7492 014 290
skype:   cirpolo

linkedin: http://linkedin.com/in/cinellialessandro
github:   http://github.com/cirpo

**Comment by liuggio** [comment]
thanks @dm 
with @cirpo we postponed http://screencloud.net/v/f48Q of 90 days... 

still todo a cronjob twice per month: with `service apache2 stop && ~/certbot-auto  certonly -d poser.pugx.org --standalone --renew-by-default; service apache2 restart`
