### ISSUE TITLE
[High Priority] Expired SSL certificate poser.pugx.org

### ISSUE THREAD

**Issue by Quezler** [PUGX/badge-poser#160]
### Dutch error
```
poser.pugx.org gebruikt een ongeldig beveiligingscertificaat.

Het certificaat is verlopen op 26 September 2016 at 14:14. De huidige tijd is 26 September 2016 at 17:05.

Foutcode: SEC_ERROR_EXPIRED_CERTIFICATE
```

### English translation

Certificate @ poser.pugx.org valid till `26 September 2016 at 14:14` has expired

**Comment by Quezler** [comment]
It appears to be a [letsencrypt](http://letsencrypt.org/) certificate, valid for only 90 days, something to keep in mind ⚠️

**Comment by Quezler** [comment]
Issue of roughly 90 days ago @ #157

**Comment by jacobfogg** [comment]
Yeah, you can't forget the auto-renew.with letsencrypt... simple'ish step, but super important. LOL

**Comment by youngbobby** [comment]
Could this be the reason why poser badges are not being displayed on repositories at the moment ?

This is what I see on all Repos using this badge system.

<img width="557" alt="screen shot 2016-09-28 at 1 12 37 pm" src="https://cloud.githubusercontent.com/assets/876261/18913072/b6c6d404-857d-11e6-8f1e-4e38fa141870.png">

**Comment by Quezler** [comment]
Yes, that is the reason i made this issue.

If you check your browser console (network tab), it will say that the SSL could not be checked for the domain the images originate from.

And thus, your browser 'protects' you by not loading the images 🙉

**Comment by liuggio** [comment]
We are migrating to docker, in few hours will be fixed

Il mer 28 set 2016 14:26 Quezler <notifications@github.com> ha scritto:

**Comment by liuggio** [comment]
done sorry for the delay our new infrastructure is new shiny and orchestrated :D
