### ISSUE TITLE
Not updating?

### ISSUE THREAD

**Issue by Svish** [PUGX/badge-poser#166]
Tried adding these badges to my [README.md](https://github.com/Svish/php-cross-domain-proxy/blob/master/README.md), but they're not showing the latest version and license?

I assume they are maybe cached? For how long?

![capture](https://cloud.githubusercontent.com/assets/142162/22639636/4137a892-ec4f-11e6-8449-0755dc0a77b2.PNG)

**Comment by liuggio** [comment]
Hi
Packagist has got a good caching mechanism for api it should be 1 h.

**Comment by Svish** [comment]
Cool, thanks! 👍
