### ISSUE TITLE
Packagist download badge does not work correctly

### ISSUE THREAD

**Issue by zeeshanu** [PUGX/badge-poser#167]
Packagist Link: [https://packagist.org/packages/zeeshanu/opus](https://packagist.org/packages/zeeshanu/opus)

![image](https://cloud.githubusercontent.com/assets/16267321/25335491/b1e9434e-290c-11e7-982d-b6882a786ab0.png)

**Comment by hpatoio** [comment]
I see `4`.

![image](https://cloud.githubusercontent.com/assets/249948/25345317/1105039c-2915-11e7-9239-5492d413564d.png)

I was probably cache.
