### ISSUE TITLE
DOCS: How long until poser picks up new package?

### ISSUE THREAD

**Issue by AlexSkrypnyk** [PUGX/badge-poser#168]
Can we please have a sentence somewhere on the page that explains how long does it take for poser to pull for new projects from packagist, even if it is instantaneous.

Thanks

**Comment by liuggio** [comment]
that's a great idea, would you like to provide this?

**Comment by alexdesignworks** [comment]
I would if I knew how it works

**Comment by wapmorgan** [comment]
What about just using any url with name of new package? It's updates instantly if package at packagist.org

**Comment by stof** [comment]
Is it actually instantaneous ? I don't get the right badge for `knplabs/knp-menu-silex`. Is it because it is a new package (and not only a new release ) ?

Btw, the search on https://poser.pugx.org does not find it.

**Comment by liuggio** [comment]
Is it ok now?

**Comment by stof** [comment]
well, it is OK now for this package now.

But it makes me think that there is a delay for badges to be updated, and this makes the request of this issue even more relevant: documenting on the website that there is such a delay, and what kind of delay it can be (is it minutes, hours or days ?)

**Comment by GinoPane** [comment]
Looking forward for this info too. Or for a button "refresh now".

**Comment by heathdutton** [comment]
It feels like a delay of at least a day?

**Comment by BenMorel** [comment]
Could the `PURGE` HTTP method be implemented, if we want to force reload a badge?

GitHub [supports this](https://stackoverflow.com/a/37000706/759866):

```
curl -X PURGE {url of cached badge image}
```

**Comment by JellyBellyDev** [comment]
in badge-poser there are no cache layers, if there are delays they are due to the bees of packagist or github! ;)

**Comment by stof** [comment]
I think github is caching images in their camo proxy.
