### ISSUE TITLE
Website is down?

### ISSUE THREAD

**Issue by Kevinrob** [PUGX/badge-poser#170]
I really like this service, but the website is down. 😭  
https://poser.pugx.org/

**Comment by Bilge** [comment]
Yes.

**Comment by jails** [comment]
The service works for me but it's lagging so much that badges are considered as dead links by github.

**Comment by HillLiu** [comment]
want to know if it's possible back or not?

**Comment by seyfer** [comment]
There is an alternative
https://shields.io/

**Comment by HillLiu** [comment]
It's back.
