### ISSUE TITLE
Switching the displayed package should update the URL

### ISSUE THREAD

**Issue by stof** [PUGX/badge-poser#172]
Each package has a canonical URL (like https://poser.pugx.org/show/knplabs/knp-menu-silex#badges), which can be accessed by clicking on the button near the package name after searching the package.
It would be great if this step was not needed, and changing the package would automatically update the URL through `history.pushState()`

**Comment by JellyBellyDev** [comment]
why? what is the advantage you see?

**Comment by stof** [comment]
Allowing to link easily to the current package page by selecting the current URL, instead of having to remember to use a different way to get the canonical URL (this is even more confusing if you perform the package search from a package page rather than from the homepage, as the current URL actually refers to a package, but not the current one).

That's about making the single-page app behave properly IMO.

**Comment by JellyBellyDev** [comment]
make sense! 
@Elfo404, could you take care of it please?

**Comment by Elfo404** [comment]
Totally makes sense, when we implemented it we didn't think of it as SPA, but it actually is. Thanks for pointing it out @stof 

I'll take a look asap, @JellyBellyDev can assign this to me?

**Comment by JellyBellyDev** [comment]
> I'll take a look asap, @JellyBellyDev can you assign this to me?

Sure!!!
