### ISSUE TITLE
Latest unstable release is calculated incorrectly

### ISSUE THREAD

**Issue by daften** [PUGX/badge-poser#174]
For some reason it always seems to take dev-master as the latest unstable. However, AFAIK dev-master should be considered lower than e.g. 0.1.0-alpha1 when using version_compare.

This repository has this behaviour, as well as https://github.com/digipolisgent/robo-drupal-console as an example.

Related to #75

**Comment by JellyBellyDev** [comment]
Hi @daften,
I analyzed the situation. In my opinion, this is not a bug.
If you want to define an unstable version you must configure the branch-alias option in extra section composer.json:
```
"extra": {
    "branch-alias": {
        "dev-master": "0.2.x-dev"
    }
}
```
I hope I have been helpful!
Can I close?

**Comment by daften** [comment]
But why would the branch-alias be needed? By default when using versions, a dev version, even on master, should be lower than a tagged version.

**Comment by nick-zh** [comment]
Hey @JellyBellyDev 

Somehow i seem to have an outdated unstable version:
https://github.com/jobcloud/messaging-lib/blob/master/composer.json

**Comment by garak** [comment]
I agree with @JellyBellyDev and I think this issue can be closed

**Comment by JellyBellyDev** [comment]
me too!
