### ISSUE TITLE
Flat format now looks identical to flat-square

### ISSUE THREAD

**Issue by Bilge** [PUGX/badge-poser#175]
Previously, `flat` was a rounded image but now it has square corners and looks identical to `flat-square`. This doesn't seem correct nor desirable.

**Comment by Bilge** [comment]
Uh, no. It's still an issue. Take a look at all the badges on [status.scriptfusion.com](http://status.scriptfusion.com/).

**Comment by Bilge** [comment]
@JellyBellyDev Please reopen this.

**Comment by JellyBellyDev** [comment]
I do not understand... I see all the badges with rounded edges...

![schermata 2018-03-11 alle 11 43 11](https://user-images.githubusercontent.com/190820/37252481-8c7fd444-2521-11e8-8c7e-43550d1ec916.png)

**Comment by Bilge** [comment]
How does that happen, the? Take a look at mine...

![image](https://user-images.githubusercontent.com/470626/37252845-7af6c832-2520-11e8-8a9e-2cf69b80427f.png)

**Comment by JellyBellyDev** [comment]
on firefox on the mac it works well!
So I also think it's just a problem of firefox on windows! 😢

**Comment by Bilge** [comment]
It seems to be very specifically just Windows 7 Firefox. Confirmed on two separate Windows 7 machines, but cannot reproduce on Windows 8 or Windows 10. It may be something to do with SVG rendering support, but I cannot say why it would be platform-specific.

**Comment by garak** [comment]
Support for Windows 7 ended on January 2020, so I guess we can close this.
