### ISSUE TITLE
All badges showing as gray

### ISSUE THREAD

**Issue by nathan-fiscaletti** [PUGX/badge-poser#177]
All of the badges seem to be showing as only gray with lines through them as of this morning. Not sure what's going on.

![image](https://user-images.githubusercontent.com/1699763/35104939-fdce5316-fc2f-11e7-9b7f-18632dd1f67d.png)

**Comment by giorrrgio** [comment]
Hi nathan,
others are reporting a packagist issue on the packagist api lib poser uses:
https://github.com/KnpLabs/packagist-api/issues/47

I see there's a PR involved, I'm not quite sure, but I fear some breaking changes where made to the packagist api recently.

**Comment by Soullivaneuh** [comment]
Hi @giorrrgio, I just tweeted KnpLabs about it: https://twitter.com/soullivaneuh/status/954075266321715200

**Comment by Jean85** [comment]
The related PR got merged, and we have the 1.5.1 fix!

**Comment by nathan-fiscaletti** [comment]
@Jean85, the problem still seems to persist though. Does PUGX need to implement a new version of the library as it’s not automated or something?

**Comment by Jean85** [comment]
@nathan-fiscaletti this is basically a Symfony app, so the 1.5.1 version of `KnpLabs/packagist-api` must be required and the app must be re-deployed by the maintainers.

**Comment by groovili** [comment]
Still a problem even in KnpLabs repository [screenshot](http://joxi.ru/L216kqbH6oDZeA)

**Comment by thunderer** [comment]
I created a PR with the package upgrade and a couple other things, could you please take a look and tell me what you think?

**Comment by Jean85** [comment]
Problem seems to be fixed, right?

**Comment by thunderer** [comment]
Right now I can see the badges but it wasn't working in today's morning. I'd still appreciate an opinion about #179.

**Comment by localheinz** [comment]
@nathan-fiscaletti 

I think this can be closed. Also see #182.
