### ISSUE TITLE
Badges render invalid images

### ISSUE THREAD

**Issue by thunderer** [PUGX/badge-poser#178]
Hi, I have also experienced the issue reported in #177 but now the situation is different - there are [no images rendered](https://github.com/thunderer/Shortcode) at all. I dug up the issue a little more and saw that on the [badges site itself](https://poser.pugx.org/) they are rendered as long gray images with some text inside. This text is [actually an exception](https://poser.pugx.org/thunderer/shortcode/version):

> exception 'Symfony\Component\Debug\Exception\ClassNotFoundException' with message 'Attempted to load class "Client" from namespace "GuzzleHttp".
Did you forget a "use" statement for e.g. "Snc\RedisBundle\Client\Phpredis\Client", "Predis\Client", "Packagist\Api\Client", "Guzzle\Service\Client", "Guzzle\Http\Client", "Symfony\Component\HttpKernel\Client", "Symfony\Component\BrowserKit\Client" or "Symfony\Bundle\FrameworkBundle\Client"?' in /var/www/bp/badge-poser3/vendor/knplabs/packagist-api/src/Packagist/Api/Client.php:186
Stack trace:
#0 {main}

Thing is, I checked the [mentioned line in `packagist-api`](https://github.com/KnpLabs/packagist-api/blob/master/src/Packagist/Api/Client.php#L186) and it looks perfectly good. I also see that the current version used in this project is correct. Do you have any idea what is happening? Maybe deployment didn't go as planned?

**Comment by localheinz** [comment]
@thunderer 

I think this can be closed, Also see #182.
