### ISSUE TITLE
Licence badge is incorrect - displays 'no' instead of license

### ISSUE THREAD

**Issue by erayd** [PUGX/badge-poser#180]
The licence badge doesn't correctly detect the licence at present - it simply displays 'no' instead.

---

![scr-20180121-123230](https://user-images.githubusercontent.com/121486/35189023-1f874b9c-fea7-11e7-9012-3c8d7413b951.png)

**Comment by curry684** [comment]
Same at https://packagist.org/packages/omines/datatables-bundle, Packagist correctly lists MIT.

**Comment by dereuromark** [comment]
I already asked the composer guys, they investigate if the error is maybe a regression in their API
If they deploy a fix, it will take a few hours to refresh the caches, they say.

**Comment by erayd** [comment]
This now appears fixed - whoever sorted this out, thank you 👍 .

**Comment by Seldaek** [comment]
Yup I fixed it yesterday it was a regression in our API, just took a while to fix everything as we cache those API calls for 12h

**Comment by curry684** [comment]
This also fixed the unstable reference along the way, was showing `dev-master` for that bundle  :)
