### ISSUE TITLE
composer.lock commit status is wrong

### ISSUE THREAD

**Issue by MrMitch** [PUGX/badge-poser#224]
For `mesavolt/named-enum`, the status of the `composer.lock` is wrong. It is detected as [![composer.lock](https://poser.pugx.org/mesavolt/named-enum/composerlock)](https://packagist.org/packages/mesavolt/named-enum)(shows uncommited ATM), but the `composer.lock` file is [actually committed to the repository](https://github.com/MesaVolt/NamedEnum/blob/develop/composer.lock).

**Comment by MrMitch** [comment]
Example output from https://poser.pugx.org/

![image](https://user-images.githubusercontent.com/576772/40306474-1bdbb8a0-5cff-11e8-8433-6ffb459a791a.png)

**Comment by JellyBellyDev** [comment]
I think that not work because your default branch is not `master` but `develop`...
Badge poser searches the file `composer.lock` inside`reponame/blob/master/composer.lock`

**Comment by Moskito89** [comment]
I believe that this issue still exist. I have problems in all of my libraries. One is here: https://bitbucket.org/wirbelwild/idml-validator 
The lock file is committed: https://bitbucket.org/wirbelwild/idml-validator/src/master/composer.lock but the badge says no: https://poser.pugx.org/bitandblack/idml-validator/composerlock

**Comment by JellyBellyDev** [comment]
I'm sorry but the tools works only the repo github hosted!
