### ISSUE TITLE
Wrong branch for unstable ?

### ISSUE THREAD

**Issue by jrfnl** [PUGX/badge-poser#227]
I'm wondering how the `unstable` branch is determined.

If no aliases RC/beta etc branches are found and no alias is passed via `composer.json`, to me, it looks like this always displays `dev-master`, while for projects using GitFlow, `master` will be the stable branch and `(dev-)develop` the unstable branch.

Could the GitHub API be used to retrieve the `default` branch and display that instead ?
The branch name can be retrieved via a call to `GET /repos/:owner/:repo` and looking at the value returned by `default_branch`.
See: https://developer.github.com/v3/repos/#get

Related #174

**Comment by JellyBellyDev** [comment]
Currently the logic goes to look for the value set for `branch-alias`, alternatively it sets `master` as value.
Would you like to do a PR using the logic you proposed in the absence of the `branch-alias` information?
You should apply the change to the new version for we are going to put online: https://github.com/PUGX/badge-poser/tree/release/v3.0.0
Thank you

**Comment by jrfnl** [comment]
> Would you like to do a PR using the logic you proposed in the absence of the branch-alias information?

No. I already spent too much time looked at the code and couldn't for the life of me figure out where to change it in this repo. If it would have been an obvious change, you would have received a PR already instead of an issue.

I haven't looked at the new repo/code yet, but can only do so much.

**Comment by JellyBellyDev** [comment]
I checked the logic.
All release prerings on packagist are taken into consideration: 
https://packagist.org/packages/digipolisgent/robo-drupal-console
On packagist there is dev-master. dev-master wins over everything on unstable.
