### ISSUE TITLE
Packagist doesn't display icons

### ISSUE THREAD

**Issue by Moskito89** [PUGX/badge-poser#232]
Viewing the README at Bitbucket displays the icons correctly: 
https://bitbucket.org/wirbelwild/contact-form
Viewing the README at Packagist returns some errors: 
https://packagist.org/packages/bitandblack/contact-form

Console output: Refused to load the image 'https://poser.pugx.org/bitandblack/contact-form/v/stable' because it violates the following Content Security Policy directive: "img-src 'self' https://www.gravatar.com/ https://*.githubusercontent.com https://raw.github.com/ https://github.com/ https://gitlab.com/ https://ssl.google-analytics.com/ http://www.google-analytics.com/". 

What is wrong here?

**Comment by JellyBellyDev** [comment]
to me it seems to work now.
close
