### ISSUE TITLE
Version bump symfony to 4.1

### ISSUE THREAD

**Issue by JellyBellyDev** [PUGX/badge-poser#237]
Version bump symfony to 4.1 on [v3.0.0](https://github.com/PUGX/badge-poser/tree/release/v3.0.0) branch.

**Comment by gnumoksha** [comment]
This issue consists in migrate all symfony dependencies to version 4.1 ? Any idea about the breaking changes one could face?

**Comment by JellyBellyDev** [comment]
do not worry @gnumoksha , I'll take care of it! Thank you

**Comment by JellyBellyDev** [comment]
There we thought!
