### ISSUE TITLE
Add tests for BadgeSubscriber

### ISSUE THREAD

**Issue by JellyBellyDev** [PUGX/badge-poser#238]
Add tests for [BadgeSubscriber](https://github.com/PUGX/badge-poser/blob/release/v3.0.0/src/EventListener/BadgeSubscriber.php) class.

**Comment by gnumoksha** [comment]
Unit tests? Any idea about edge cases that must be tested?

**Comment by JellyBellyDev** [comment]
Yep unit tests! The public function! ;)

**Comment by JellyBellyDev** [comment]
it has been done! 🚀
