### ISSUE TITLE
Add tests for Stats 

### ISSUE THREAD

**Issue by JellyBellyDev** [PUGX/badge-poser#239]
Add tests for [Stats](https://github.com/PUGX/badge-poser/tree/release/v3.0.0/src/Stats) domain.

**Comment by gnumoksha** [comment]
Unit tests? Any idea about edge cases that must be tested?

**Comment by JellyBellyDev** [comment]
Yep unit tests! The public function! ;)

**Comment by DonCallisto** [comment]
See https://github.com/PUGX/badge-poser/pull/391

**Comment by JellyBellyDev** [comment]
it has been done! 🚀
