### ISSUE TITLE
500 error on my package

### ISSUE THREAD

**Issue by paul-thebaud** [PUGX/badge-poser#286]
Hello,

The server is returning a 500 HTTP status response when querying for my package.
Here is the URL : https://poser.pugx.org/snippet/all/?repository=phpunitgen%2Fconsole

Is this a bug or something my package does not contains?

Thanks.

**Comment by JellyBellyDev** [comment]
Thanks for the report, we currently have delivery problems.

**Comment by JellyBellyDev** [comment]
We're back: https://poser.pugx.org/show/phpunitgen/console#badges ;)

**Comment by paul-thebaud** [comment]
Nice, thanks for this quick fix !
