### ISSUE TITLE
[UI/Frontend] General improvements / fixes

### ISSUE THREAD

**Issue by Elfo404** [PUGX/badge-poser#316]
I'm creating this umbrella issue as a follow up to a discussion with @JellyBellyDev to gather feedback and opinions on possible improvements on the frontend so that I can start addressing some of them.

## What I would like to do:

- add an `.nvmrc' file
- Update dependencies
- Style improvements
- Properly make this work as a single page app as suggested in #172, with a better implementation than what I did in #310 
- Better responsive styles

Any other suggestion?

I'll keep updating this.

**Comment by JellyBellyDev** [comment]
* in the autocomplete input the spinner overlaps the `x`

**Comment by JellyBellyDev** [comment]
* reduce headlines and buttons in the mobile version?

**Comment by JellyBellyDev** [comment]
* when we show the badge preview make the images real previews with the appropriate link `target="blank"`?

**Comment by JellyBellyDev** [comment]
> * in the autocomplete input the spinner overlaps the `x`

done here: https://github.com/PUGX/badge-poser/pull/558

**Comment by JellyBellyDev** [comment]
it's all done except "reduce headlines and buttons in the mobile version?" I move this issue in other anche i clone this! ;)
