### ISSUE TITLE
Badges don't load

### ISSUE THREAD

**Issue by Moskito89** [PUGX/badge-poser#336]
All of my packages have blank grey badges since a few days. 
For example in [kiwa/core](https://packagist.org/packages/kiwa/core), the version badge is [here](https://poser.pugx.org/kiwa/core/v).
Searching for the package at [https://poser.pugx.org](https://poser.pugx.org/show/kiwa/core) brings the same result...

Where is this problem coming from? What can I do now? 
Thanks in advance!

**Comment by JellyBellyDev** [comment]
Hi @Moskito89, thanks for the notice!  
I'm sorry but actually badge-poser don't support source-code hosted on bitbucket or gitlab!  
We will try to add support as soon as possible!

**Comment by Moskito89** [comment]
Thanks for the information. This is a little bit frustrating, because the badges used to work and now I have grey icons in all of my packages. :-(

**Comment by JellyBellyDev** [comment]
I'm so sorry @Moskito89!
We put the support for bitbucket back on the roadmap!

**Comment by Moskito89** [comment]
Thank you, @JellyBellyDev! (Y)

**Comment by JellyBellyDev** [comment]
@Moskito89 support for bitbucket online: https://poser.pugx.org/show/kiwa/core 🚀

**Comment by Moskito89** [comment]
Works perfectly! Thank you very much!
