### ISSUE TITLE
Add support to sources hosted on bitbucket

### ISSUE THREAD

**Issue by JellyBellyDev** [PUGX/badge-poser#337]
### Feature Request

Add support to sources hosted on bitbucket

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary

Try to use this library https://github.com/BitbucketAPI/Client as client to talk with bitbucket!
Use case: [kiwa/core](https://packagist.org/packages/kiwa/core)

Ref: #336

**Comment by AlessandroMinoccheri** [comment]
Closed by #338
