### ISSUE TITLE
Error: Incorrect whitelist config, no code coverage will be generated.

### ISSUE THREAD

**Issue by DonCallisto** [PUGX/badge-poser#392]
Related to https://github.com/PUGX/badge-poser/pull/391
See the build: https://app.circleci.com/pipelines/github/PUGX/badge-poser/282/workflows/8b32270e-4bf6-4c74-89af-53242dd10e0b/jobs/1162

**Comment by DonCallisto** [comment]
See https://github.com/PUGX/badge-poser/pull/393

BTW I don't see any tool to collect the result of code coverage. Is it intended or is it missing?

**Comment by JellyBellyDev** [comment]
was on the todo list of things to do!

**Comment by DonCallisto** [comment]
There's an issue that I can tackle, or was just an "abstract" to do? Because I can set it up in a different PR.
If there's not an issue related, what provider (coveralls, codecov, etc) do you prefer?

**Comment by JellyBellyDev** [comment]
Unfortunately there is no issue, we talked about it on slack!
I have no preferences about it! I leave the choice to the creator, the important thing is that we can then use a badge that shows the percentage in the readme! ;)

**Comment by DonCallisto** [comment]
Ok. I'll work at this next days.

**Comment by DonCallisto** [comment]
I think this could be closed.
