### ISSUE TITLE
poser.pugx.org is down

### ISSUE THREAD

**Issue by MarcinOrlowski** [PUGX/badge-poser#403]
I am constantly getting timeouts. Also https://downforeveryoneorjustme.com/poser.pugx.org confirms

**Comment by JellyBellyDev** [comment]
We are so sorry ... we are working hard to improve the stability of the architecture!

**Comment by MarcinOrlowski** [comment]
Seems to work now. Thanks for great servce! Feel free to close unless it serves other purposes.
