### ISSUE TITLE
Limit number of results

### ISSUE THREAD

**Issue by garak** [PUGX/badge-poser#408]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | no
| RFC         | yes
| BC Break    | no

#### Summary

Currently, when you search for a package, the autocomplete returns an undefined amount of results.
For example, if you start to search for a symfony package, the following URL is called via ajax: `https://poser.pugx.org/search_packagist?name=sym`
Such URL is returning a json of 1000 (**one thoushand**!) objects, while the user interface shows only first 10 results.

I think this is a big waste of resources: we should limit search results to 10 results (or maybe to 20, just to leave room for a bigger space in UI)

**Comment by AlessandroMinoccheri** [comment]
Ok, I think it's necessary to do it.
Have you thought about creating a page to view all results or something similar?
Or is it not necessary?

**Comment by garak** [comment]
Since we're talking about an autocomplete, there's no need to see all results.

I would to add a request: please do not open a PR to solve this issue now, we would like to keep it for our [Hacktoberfest](https://www.meetup.com/it-IT/PUG-Roma/events/274058045/)
