### ISSUE TITLE
Version badge shows incorrect version

### ISSUE THREAD

**Issue by MarcinOrlowski** [PUGX/badge-poser#410]
I recently noticed that version badge reports incorrect version. The package is https://github.com/MarcinOrlowski/laravel-api-response-builder and recent version is **9**.0.1, but badge says **8**.0.1. Also `dev` badge is choosen oddly. There's `dev` branch, so why it picks `7.x` (not to mention there's `8.x` as well)?

![v](https://user-images.githubusercontent.com/8041294/96878475-32c16480-147b-11eb-8ba7-3df34448ad19.png)

![p](https://user-images.githubusercontent.com/8041294/96878318-fc83e500-147a-11eb-9113-cd1661f15f0e.png)

**Comment by JellyBellyDev** [comment]
Hi @MarcinOrlowski ,
thanks to reporting! We have a layer of cache to show the version, for this you did not notice the updated version! 9.0.1 is now shown correctly!
For the unstable version we wait a little longer and you should see the correct one for him too! ;)

**Comment by MarcinOrlowski** [comment]
> We have a layer of cache to show the version

I still there's something more than cache. IIRC version badge used to show version 9.0.0 already correctly, but now it shows 8.0.1 so it's not cached version. It's a wrong one.

> For the unstable version we wait a little longer and you should see the correct one for him too! ;)

This was never correctly shown. I never saw `dev` or `dev-dev` - always some other branches.

**Comment by JellyBellyDev** [comment]
> > We have a layer of cache to show the version
> 
> I still there's something more than cache. IIRC version badge used to show version 9.0.0 already correctly, but now it shows 8.0.1 so it's not cached version. It's a wrong one.

I don't understand i see the correct version:

![Schermata 2020-10-23 alle 13 59 29](https://user-images.githubusercontent.com/190820/97001078-10415100-1538-11eb-85e0-8de39e034d95.png)

> 
> > For the unstable version we wait a little longer and you should see the correct one for him too! ;)
> 
> This was never correctly shown. I never saw `dev` or `dev-dev` - always some other branches.

@AlessandroMinoccheri please can you check this? Thanks!

**Comment by AlessandroMinoccheri** [comment]
I can see the correct version.
Could it be a cache problem somewhere?

**Comment by MarcinOrlowski** [comment]
Not sure. I see correct version for now too. If you see no possibility to be an backend issue, I am closing this ticket now as I cannot provide any additional information. Would reopen if issue reoccured.

**Comment by rob006** [comment]
There is something wrong with this cache. For https://packagist.org/packages/rob006/flarum-lang-polish I have `v0.3.14` on https://poser.pugx.org/rob006/flarum-lang-polish/v/stable, while `v0.3.15` was released 3 months ago. So if it is cache, it is outdated by 3 months. 
Curiously https://poser.pugx.org/rob006/flarum-lang-polish/v/stable?1 displays correct version.

Same with downloads counter:
767 on https://poser.pugx.org/rob006/flarum-lang-polish/downloads
873 on https://poser.pugx.org/rob006/flarum-lang-polish/downloads?1

**Comment by rob006** [comment]
BTW: Examples above for version and downloads count works fine already, but monthly downloads are still outdated:

24 - https://poser.pugx.org/rob006/flarum-lang-polish/d/monthly
59 - https://poser.pugx.org/rob006/flarum-lang-polish/d/monthly?1

**Comment by JellyBellyDev** [comment]
Linked to this issue: https://github.com/PUGX/badge-poser/issues/478

**Comment by a-menshchikov** [comment]
I have the same problem with https://github.com/hslavich/OneloginSamlBundle
Actual latest stable version is 2.3.0, but "bager" detect it as 2.2.2 (that was released half an hour earlier).

**Comment by JellyBellyDev** [comment]
![Schermata 2021-06-01 alle 10 51 07](https://user-images.githubusercontent.com/190820/120295262-46f9f980-c2c7-11eb-86da-2e85c08b767b.png)

sure? :)

**Comment by a-menshchikov** [comment]
@JellyBellyDev it was exactly an half-hour ago.
It seems like a cache bug, but I have no idea where to look for it.

**Comment by a-menshchikov** [comment]
![image](https://user-images.githubusercontent.com/2580489/120342024-12eefa80-c300-11eb-9eec-db6c320c4f25.png)
I see some less downloads count. =\

**Comment by a-menshchikov** [comment]
@JellyBellyDev the bug with cache came back for https://github.com/hslavich/OneloginSamlBundle =(

**Comment by JellyBellyDev** [comment]
Now i can see this:

![Schermata 2021-07-15 alle 09 51 45](https://user-images.githubusercontent.com/190820/125750527-26b28ad0-eb59-477c-b5dc-92cccbe40b84.png)

Where was the problem?

**Comment by a-menshchikov** [comment]
@JellyBellyDev 
Maybe I'm missing something: how long does pugx cache invalidate? I have released v2.4.2 at the morning yesterday, but after 15 hours the badge had still shown v2.4.1.

**Comment by JellyBellyDev** [comment]
two hours, but consider that also the packagist api use a cache and I don't know what its TTL!

**Comment by Bilge** [comment]
Now they all show "No Release", for all packages.

**Comment by JellyBellyDev** [comment]
Thanks for reporting @Bilge! We have fix the regression! ;)

**Comment by jcubic** [comment]
Is there a way to purge the cache? GitHub images are cached by GitHub and those images are also cached by the browser. To clear the cache for images on GitHub you can use curl from GitHub action. And then clear the browser cache. But still, it would be nice to be able to clear the badge on the PUGX side before clearing the GitHub cache. Otherwise, it doesn't make sense.

**Comment by terremoth** [comment]
my repo has a stable version too, and is showing "stable | no release" but there are some releases already

https://github.com/terremoth/php-dsv

**Comment by JellyBellyDev** [comment]
> my repo has a stable version too, and is showing "stable | no release" but there are some releases already

@terremoth everything seems ok to me, or am I wrong?  
https://poser.pugx.org/show/terremoth/php-dsv

**Comment by terremoth** [comment]
@JellyBellyDev now it is showing correctly. Maybe was the cache.

**Comment by JellyBellyDev** [comment]
Close! ;)
