### ISSUE TITLE
Improve performances

### ISSUE THREAD

**Issue by garak** [PUGX/badge-poser#412]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | no
| RFC         | yes
| BC Break    |no

#### Summary

We could improve loading speed in homepage. I see two possible points (maybe other can be proposed):

* use smaller images for contributors
* load such images lazily

**Comment by JellyBellyDev** [comment]
I love the big image for the contributors!
I prefer the second proposal! ;)

**Comment by garak** [comment]
> I love the big image for the contributors!

Question is: we display images in 160x160 size, while we grab it from github in 400x400 size.

**Comment by JellyBellyDev** [comment]
> > I love the big image for the contributors!
> 
> Question is: we display images in 160x160 size, while we grab it from github in 400x400 size.

I know but the alternative by github is 80x80...

**Comment by garak** [comment]
> I know but the alternative by github is 80x80...

Are you sure? https://avatars2.githubusercontent.com/u/190820?s=160

**Comment by JellyBellyDev** [comment]
in the past in the response of the bees there was no this format ... maybe it was added recently or maybe it is not standard and its online maintenance is not guaranteed.

**Comment by garak** [comment]
I see that is specified in official docs, for example https://styleguide.github.com/primer/components/avatars/

**Comment by JellyBellyDev** [comment]
great! then we could apply both points proposed! ;)
