### ISSUE TITLE
"Client::AUTH_HTTP_TOKEN" authentication method is deprecated

### ISSUE THREAD

**Issue by JellyBellyDev** [PUGX/badge-poser#413]
`INFO   | PHP    User Deprecated: Using the "Client::AUTH_HTTP_TOKEN" authentication method is deprecated in knp-labs/php-github-api v2.15 and will be removed in knp-labs/php-github-api v3.0. Use "Client::AUTH_ACCESS_TOKEN" instead.`

what do you think if we upgrade the client version?

**Comment by AlessandroMinoccheri** [comment]
IMHO we can try to upgrade the client version.

**Comment by JellyBellyDev** [comment]
it has been fixed! 🚀
