### ISSUE TITLE
Copy all badges uses the phpunit/phpunit urls

### ISSUE THREAD

**Issue by williamdes** [PUGX/badge-poser#445]
"Copy all badges" uses the phpunit/phpunit urls
![image](https://user-images.githubusercontent.com/7784660/100328671-10b48800-2fcd-11eb-9cfd-fb84f8bf6489.png)

```
[![Latest Stable Version](https://poser.pugx.org/phpunit/phpunit/v)](//packagist.org/packages/phpunit/phpunit) [![Total Downloads](https://poser.pugx.org/phpunit/phpunit/downloads)](//packagist.org/packages/phpunit/phpunit) [![Latest Unstable Version](https://poser.pugx.org/phpunit/phpunit/v/unstable)](//packagist.org/packages/phpunit/phpunit) [![License](https://poser.pugx.org/phpunit/phpunit/license)](//packagist.org/packages/phpunit/phpunit)
```

**Comment by JellyBellyDev** [comment]
@williamdes thanks for reporting!

**Comment by JellyBellyDev** [comment]
@fabiocicerchia this fix is on the master! Please can you do a new deploy?

**Comment by fabiocicerchia** [comment]
It has been deployed on 6th Dec 2020 around 4PM. Could you please confirm it is fine?
Thank you ;)

**Comment by williamdes** [comment]
> It has been deployed on 6th Dec 2020 around 4PM. Could you please confirm it is fine?
> Thank you ;)

Confirmed, thank you everybody !
