### ISSUE TITLE
Badge shows very old stable release

### ISSUE THREAD

**Issue by ondrejmirtes** [PUGX/badge-poser#497]
### Bug Report

The latest release in phpstan/phpstan repo is 0.12.81, but the badge still shows 0.12.42: https://poser.pugx.org/phpstan/phpstan/v/stable

Thank you for this service, I'm very happy with it most of the time ❤️

**Comment by AlessandroMinoccheri** [comment]
Hi @ondrejmirtes we did some fixes, have you still encountered problems?

**Comment by ondrejmirtes** [comment]
It's fine, thank you very much!
