### ISSUE TITLE
Add php version badge (and maybe other dependencies)

### ISSUE THREAD

**Issue by VincentLanglet** [PUGX/badge-poser#607]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes
| BC Break    | no

#### Summary

According to the tests fixtures
https://raw.githubusercontent.com/PUGX/badge-poser/f71d0b72d22f481fdccf52f426eba3a59831b189/tests/Badge/Model/fixtures/packages/imagine-bundle.json
when the call is made to packagist, the `require` section is provided.

So a badge
```
php: >=5.3.2
```
could be possible

This would allow people to know directly in the Readme the compatible version without looking at the composer.json. (and it will be always up to date with the last version)

I think about this especially for the php version but there might be some interest for some other dependencies version...

**Comment by AlessandroMinoccheri** [comment]
Thanks, @VincentLanglet!
I think it's a good idea and we can work to implement it.
