### ISSUE TITLE
Add a way for different styled badges

### ISSUE THREAD

**Issue by ricardoboss** [PUGX/badge-poser#705]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes
| BC Break    | no

#### Summary

I'd like to be able to specify different styles for badges, namely `plastic`, `flat`, `flat-squared` and (maybe) `for-the-badge`.

| style | example 
|---|---
| `plastic` | ![image](https://user-images.githubusercontent.com/6266356/150658644-d149fbfa-05f7-427c-971f-3338b647ad31.png)
| `flat` | ![image](https://user-images.githubusercontent.com/6266356/150658639-cac751dd-7b33-4e35-8cb3-e77048728762.png)
| `flat-squared` | ![image](https://user-images.githubusercontent.com/6266356/150658648-45179c28-0900-47dc-83d2-3d7cd7edceff.png)
| `for-the-badge` | ![image](https://user-images.githubusercontent.com/6266356/150658651-3894e715-1898-42e6-8b47-ee77ea42f2f0.png)

I think some are already possible, but it's not documented anywhere and I was unable to find any through trial and error. What do you think?

**Comment by JellyBellyDev** [comment]
I also remember this feature in previous versions. I'm afraid we lost them with the 3.0 upgrade.  
Would you like to try to restore them?

**Comment by ricardoboss** [comment]
Yes, I can dig into this and try to restore them. If I run into problems I'll ping you here, ok?

**Comment by JellyBellyDev** [comment]
Of course! Thanks so much! 😎

**Comment by JellyBellyDev** [comment]
**Tips**
- library used: `badges/poser`
- in the old docs I found this: https://github.com/PUGX/badge-poser/blob/v2.2.3/src/PUGX/BadgeBundle/Resources/views/Page/home.html.twig#L239

**Comment by ricardoboss** [comment]
@JellyBellyDev everything done. I suppose I will need to update some docs as well.

**Comment by JellyBellyDev** [comment]
Assume well! ;)
https://github.com/PUGX/badge-poser/pull/707#issuecomment-1023228591

**Comment by ricardoboss** [comment]
Another possible solution if the data is available in JSON: shields.io

**Comment by JellyBellyDev** [comment]
I would prefer not to make our product dependent on an additional external service (shields.io)...

**Comment by ricardoboss** [comment]
No, I meant not as an alternative renderer, but rather as an alternative to badge-poser.

**Comment by JellyBellyDev** [comment]
So would you like to throw all this good work you've done in the trash?

**Comment by ricardoboss** [comment]
No of course not, but future visitors might want to consider alternatives.

**Comment by JellyBellyDev** [comment]
I'm sorry but I'm not understanding. What are you proposing to do? :)

**Comment by ricardoboss** [comment]
I'm not proposing anything. I just wanted to tell future visitors of this issue (maybe found via Google) that there may be no need to use `badge-poser` if you have all information you want to display on your badge available via JSON.

This applied to my use-case, so I no longer need to use badge-poser and my issue is no longer _my_ issue. I will of course still work on my PRs to fix this issue for everyone not being able to use shields.io.

**Comment by JellyBellyDev** [comment]
Ok, now it's all clear to me. Thank you

**Comment by ricardoboss** [comment]
Waiting for https://github.com/badges/poser/pull/89 to get merged so a new version of it can be released. Once that happened, I can update and merge https://github.com/PUGX/badge-poser/pull/733 to fix this issue :)

**Comment by JellyBellyDev** [comment]
Hey @ricardoboss, you are online! 🚀

**Comment by ricardoboss** [comment]
Thank you @JellyBellyDev for your support!
