### ISSUE TITLE
Removing parameters from services adding dictionaries

### ISSUE THREAD

**Issue by AlessandroMinoccheri** [PUGX/badge-poser#769]
### Feature Request

Removing parameters from services adding dictionaries

|    Q        |   A
|------------ | ------
| New Feature | no
| RFC         | yes
| BC Break    | yes

#### Summary

I am thinking to remove all parameters from services file like:

```
pugx_badge_allin_badges
pugx_badge_badges
```

In my opinion, is better to have dictionary files to store this information and remove dependencies parameters into `SnippetGenerator.php`.
In that service, we can call statically those dictionary files instead of injecting parameters array from services file.

What do you think?

I can work into this pull request if it can be of value for this project.
I think it can be a BC because we are changing SnippetGenerator constructor.

**Comment by JellyBellyDev** [comment]
It's a nice idea to me! It's an improvement also to DX side to the maintainability of the software.  
Thanks @AlessandroMinoccheri
